import React from "react";
import type { Metadata } from "next";
import Navbar from "./components/Navbar";
import './globals.css'; // Importa el archivo de Tailwind




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gray-800 text-white flex flex-col">
        <Navbar/>
     
      <main className="flex-grow container mx-auto p-4">
        {children}
      </main>
      </body>
    </html>
  )
}

export default Layout;

